/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.HashMap;
import javax.swing.JOptionPane;
import modelo.Propiedad;
import controlador.*;
import java.util.Set;

/**
 *
 * @author santh
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorConsultas = new javax.swing.JPanel();
        botonPrestamosMasCuotas = new javax.swing.JButton();
        botonPopiedadMasHipotecada = new javax.swing.JButton();
        botonPrestamosMenosCuotas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonPrestamosMayorMenorMonto = new javax.swing.JButton();
        botonMetrosCubiertosCasasDepartamentos = new javax.swing.JButton();
        botonPersonasHipotecasTodosDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorConsultas.setBackground(new java.awt.Color(255, 255, 255));
        contenedorConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPrestamosMasCuotas.setBackground(new java.awt.Color(0, 134, 190));
        botonPrestamosMasCuotas.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPrestamosMasCuotas.setText("Personas con prestamos de mas cuotas");
        botonPrestamosMasCuotas.setBorder(null);
        botonPrestamosMasCuotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrestamosMasCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamosMasCuotasActionPerformed(evt);
            }
        });
        contenedorConsultas.add(botonPrestamosMasCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 450, 50));

        botonPopiedadMasHipotecada.setBackground(new java.awt.Color(0, 134, 190));
        botonPopiedadMasHipotecada.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPopiedadMasHipotecada.setText("Tipo Propiedad mas Hipotecada");
        botonPopiedadMasHipotecada.setBorder(null);
        botonPopiedadMasHipotecada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPopiedadMasHipotecada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPopiedadMasHipotecadaActionPerformed(evt);
            }
        });
        contenedorConsultas.add(botonPopiedadMasHipotecada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 450, 50));

        botonPrestamosMenosCuotas.setBackground(new java.awt.Color(0, 134, 190));
        botonPrestamosMenosCuotas.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPrestamosMenosCuotas.setText("Personas con prestamos de menos cuotas");
        botonPrestamosMenosCuotas.setBorder(null);
        botonPrestamosMenosCuotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrestamosMenosCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamosMenosCuotasActionPerformed(evt);
            }
        });
        contenedorConsultas.add(botonPrestamosMenosCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 450, 50));

        jPanel1.setBackground(new java.awt.Color(0, 134, 190));

        botonVolver.setBackground(new java.awt.Color(0, 134, 190));
        botonVolver.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_2.png"))); // NOI18N
        botonVolver.setMnemonic('\u0006');
        botonVolver.setText("  Volver");
        botonVolver.setBorder(null);
        botonVolver.setBorderPainted(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonVolver.setMaximumSize(new java.awt.Dimension(179, 129));
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverMouseClicked(evt);
            }
        });
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorConsultas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 60));

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setText("CONSULTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(322, 322, 322))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        contenedorConsultas.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        botonPrestamosMayorMenorMonto.setBackground(new java.awt.Color(0, 134, 190));
        botonPrestamosMayorMenorMonto.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPrestamosMayorMenorMonto.setText("Prestamos con mayor y menor monto");
        botonPrestamosMayorMenorMonto.setBorder(null);
        botonPrestamosMayorMenorMonto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrestamosMayorMenorMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamosMayorMenorMontoActionPerformed(evt);
            }
        });
        contenedorConsultas.add(botonPrestamosMayorMenorMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 450, 50));

        botonMetrosCubiertosCasasDepartamentos.setBackground(new java.awt.Color(0, 134, 190));
        botonMetrosCubiertosCasasDepartamentos.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonMetrosCubiertosCasasDepartamentos.setText("Promedio en m2 de casas y depto hipotecados");
        botonMetrosCubiertosCasasDepartamentos.setBorder(null);
        botonMetrosCubiertosCasasDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonMetrosCubiertosCasasDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMetrosCubiertosCasasDepartamentosActionPerformed(evt);
            }
        });
        contenedorConsultas.add(botonMetrosCubiertosCasasDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 450, 50));

        botonPersonasHipotecasTodosDatos.setBackground(new java.awt.Color(0, 134, 190));
        botonPersonasHipotecasTodosDatos.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPersonasHipotecasTodosDatos.setText("Personas con hipotecas y todos sus datos");
        botonPersonasHipotecasTodosDatos.setBorder(null);
        botonPersonasHipotecasTodosDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPersonasHipotecasTodosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonasHipotecasTodosDatosActionPerformed(evt);
            }
        });
        contenedorConsultas.add(botonPersonasHipotecasTodosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 450, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPrestamosMasCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamosMasCuotasActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPrestamosMasCuotasActionPerformed

    private void botonPopiedadMasHipotecadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPopiedadMasHipotecadaActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPopiedadMasHipotecadaActionPerformed

    private void botonPrestamosMenosCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamosMenosCuotasActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPrestamosMenosCuotasActionPerformed

    private void botonPrestamosMayorMenorMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamosMayorMenorMontoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPrestamosMayorMenorMontoActionPerformed

    private void botonMetrosCubiertosCasasDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMetrosCubiertosCasasDepartamentosActionPerformed

        this.hide();
        PromedioM2Hipotecas h = new PromedioM2Hipotecas();
        h.setVisible(true);



    }//GEN-LAST:event_botonMetrosCubiertosCasasDepartamentosActionPerformed

    private void botonPersonasHipotecasTodosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonasHipotecasTodosDatosActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPersonasHipotecasTodosDatosActionPerformed

    private void botonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMouseClicked

    }//GEN-LAST:event_botonVolverMouseClicked

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.hide();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMetrosCubiertosCasasDepartamentos;
    private javax.swing.JButton botonPersonasHipotecasTodosDatos;
    private javax.swing.JButton botonPopiedadMasHipotecada;
    private javax.swing.JButton botonPrestamosMasCuotas;
    private javax.swing.JButton botonPrestamosMayorMenorMonto;
    private javax.swing.JButton botonPrestamosMenosCuotas;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel contenedorConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
