/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author MultiRepair
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorHome = new javax.swing.JPanel();
        botonPropietariosHome = new javax.swing.JButton();
        botonPrestamosHome = new javax.swing.JButton();
        botonInmueblesHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonInicioCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonConsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        contenedorHome.setBackground(new java.awt.Color(255, 255, 255));
        contenedorHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPropietariosHome.setBackground(new java.awt.Color(0, 134, 190));
        botonPropietariosHome.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPropietariosHome.setText("Propietarios");
        botonPropietariosHome.setBorder(null);
        botonPropietariosHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPropietariosHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPropietariosHomeActionPerformed(evt);
            }
        });
        contenedorHome.add(botonPropietariosHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 280, 50));

        botonPrestamosHome.setBackground(new java.awt.Color(0, 134, 190));
        botonPrestamosHome.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonPrestamosHome.setText("Prestamos");
        botonPrestamosHome.setBorder(null);
        botonPrestamosHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrestamosHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamosHomeActionPerformed(evt);
            }
        });
        contenedorHome.add(botonPrestamosHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 280, 50));

        botonInmueblesHome.setBackground(new java.awt.Color(0, 134, 190));
        botonInmueblesHome.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonInmueblesHome.setText("Inmuebles");
        botonInmueblesHome.setBorder(null);
        botonInmueblesHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonInmueblesHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInmueblesHomeActionPerformed(evt);
            }
        });
        contenedorHome.add(botonInmueblesHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 280, 50));

        jPanel1.setBackground(new java.awt.Color(0, 134, 190));

        botonInicioCerrarSesion.setBackground(new java.awt.Color(0, 134, 190));
        botonInicioCerrarSesion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonInicioCerrarSesion.setText("Cerrar Sesion");
        botonInicioCerrarSesion.setBorder(null);
        botonInicioCerrarSesion.setBorderPainted(false);
        botonInicioCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicioCerrarSesion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonInicioCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioCerrarSesionMouseClicked(evt);
            }
        });
        botonInicioCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(672, Short.MAX_VALUE)
                .addComponent(botonInicioCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(botonInicioCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        contenedorHome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 60));

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setText("INICIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        contenedorHome.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        botonConsultas.setBackground(new java.awt.Color(0, 134, 190));
        botonConsultas.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonConsultas.setText("Consultas");
        botonConsultas.setBorder(null);
        botonConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });
        contenedorHome.add(botonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPropietariosHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPropietariosHomeActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPropietariosHomeActionPerformed

    private void botonPrestamosHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamosHomeActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonPrestamosHomeActionPerformed

    private void botonInmueblesHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInmueblesHomeActionPerformed
        Inmuebles a = new Inmuebles();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonInmueblesHomeActionPerformed

    private void botonInicioCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioCerrarSesionMouseClicked

    }//GEN-LAST:event_botonInicioCerrarSesionMouseClicked

    private void botonInicioCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioCerrarSesionActionPerformed
        InicioSesion a = new InicioSesion();
        a.setVisible(true);
        this.setVisible(false);
        

    }//GEN-LAST:event_botonInicioCerrarSesionActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        Consultas a = new Consultas();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonInicioCerrarSesion;
    private javax.swing.JButton botonInmueblesHome;
    private javax.swing.JButton botonPrestamosHome;
    private javax.swing.JButton botonPropietariosHome;
    private javax.swing.JPanel contenedorHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
