/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author MultiRepair
 */
public class Prestamos extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrestamos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        botonCargarPrestamo = new javax.swing.JButton();
        botonVerPrestamo = new javax.swing.JButton();
        botonModificarPrestamo = new javax.swing.JButton();
        botonEliminarPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        contenedorPrestamos.setBackground(new java.awt.Color(255, 255, 255));
        contenedorPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 134, 190));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setText("PRESTAMO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(329, 329, 329))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        contenedorPrestamos.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        botonVolver.setBackground(new java.awt.Color(0, 134, 190));
        botonVolver.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_2.png"))); // NOI18N
        botonVolver.setMnemonic('\u0006');
        botonVolver.setText("  Volver");
        botonVolver.setBorder(null);
        botonVolver.setBorderPainted(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonVolver.setMaximumSize(new java.awt.Dimension(179, 129));
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverMouseClicked(evt);
            }
        });
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorPrestamos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 60));

        botonCargarPrestamo.setBackground(new java.awt.Color(0, 134, 190));
        botonCargarPrestamo.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonCargarPrestamo.setText("Ver Prestamo");
        botonCargarPrestamo.setBorder(null);
        botonCargarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonCargarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPrestamoActionPerformed(evt);
            }
        });
        contenedorPrestamos.add(botonCargarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 280, 50));

        botonVerPrestamo.setBackground(new java.awt.Color(0, 134, 190));
        botonVerPrestamo.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonVerPrestamo.setText("Cargar Prestamo");
        botonVerPrestamo.setBorder(null);
        botonVerPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonVerPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPrestamoActionPerformed(evt);
            }
        });
        contenedorPrestamos.add(botonVerPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 280, 50));

        botonModificarPrestamo.setBackground(new java.awt.Color(0, 134, 190));
        botonModificarPrestamo.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonModificarPrestamo.setText("Modificar Prestamo");
        botonModificarPrestamo.setBorder(null);
        botonModificarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonModificarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPrestamoActionPerformed(evt);
            }
        });
        contenedorPrestamos.add(botonModificarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 280, 50));

        botonEliminarPrestamo.setBackground(new java.awt.Color(0, 134, 190));
        botonEliminarPrestamo.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonEliminarPrestamo.setText("Eliminar Prestamo");
        botonEliminarPrestamo.setBorder(null);
        botonEliminarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPrestamoActionPerformed(evt);
            }
        });
        contenedorPrestamos.add(botonEliminarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrestamos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPrestamoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonCargarPrestamoActionPerformed

    private void botonVerPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPrestamoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonVerPrestamoActionPerformed

    private void botonModificarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPrestamoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonModificarPrestamoActionPerformed

    private void botonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMouseClicked

    }//GEN-LAST:event_botonVolverMouseClicked

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.hide();
        Home h=new Home();
        h.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPrestamoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcion en construccion");
    }//GEN-LAST:event_botonEliminarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarPrestamo;
    private javax.swing.JButton botonEliminarPrestamo;
    private javax.swing.JButton botonModificarPrestamo;
    private javax.swing.JButton botonVerPrestamo;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel contenedorPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
