/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LecturaArchivoInmueble;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modelo.Casa;
import modelo.Departamento;
import modelo.Propiedad;

/**
 *
 * @author MultiRepair
 */
public class VerInmueble extends javax.swing.JFrame {

    /**
     * Creates new form VerInmueble
     */
    public void bloquearJtextField() {
        jDireccion.setEditable(false);
        jAmbientes.setEditable(false);
        jAntiguedad.setEditable(false);
        jValor.setEditable(false);
        jCubiertos.setEditable(false);
        jTotales.setEditable(false);
        jPiso.setEditable(false);
        jIdentificador.setEditable(false);
    }

    public VerInmueble() {
        initComponents();
        bloquearJtextField();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorVerInmueble = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonVolverVerInmueble = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDni = new javax.swing.JTextField();
        jDireccion = new javax.swing.JTextField();
        jBuscar = new javax.swing.JButton();
        jValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jAmbientes = new javax.swing.JTextField();
        jCubiertos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTotales = new javax.swing.JTextField();
        jIdentificador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jAntiguedad = new javax.swing.JTextField();
        jPiso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorVerInmueble.setBackground(new java.awt.Color(255, 255, 255));
        contenedorVerInmueble.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 134, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel2.setText("VER INMUEBLE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedorVerInmueble.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        botonVolverVerInmueble.setBackground(new java.awt.Color(0, 134, 190));
        botonVolverVerInmueble.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonVolverVerInmueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_2.png"))); // NOI18N
        botonVolverVerInmueble.setMnemonic('\u0006');
        botonVolverVerInmueble.setText("  Volver");
        botonVolverVerInmueble.setBorder(null);
        botonVolverVerInmueble.setBorderPainted(false);
        botonVolverVerInmueble.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolverVerInmueble.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonVolverVerInmueble.setMaximumSize(new java.awt.Dimension(179, 129));
        botonVolverVerInmueble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverVerInmuebleMouseClicked(evt);
            }
        });
        botonVolverVerInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverVerInmuebleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonVolverVerInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolverVerInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorVerInmueble.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 60));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Documento");
        contenedorVerInmueble.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 27));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Direccion ");
        contenedorVerInmueble.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        jDni.setBackground(new java.awt.Color(255, 255, 255));
        jDni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDniActionPerformed(evt);
            }
        });
        contenedorVerInmueble.add(jDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 440, 25));
        jDni.getAccessibleContext().setAccessibleDescription("");

        jDireccion.setBackground(new java.awt.Color(255, 255, 255));
        jDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDireccionActionPerformed(evt);
            }
        });
        contenedorVerInmueble.add(jDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 440, 25));
        jDireccion.getAccessibleContext().setAccessibleDescription("");

        jBuscar.setBackground(new java.awt.Color(0, 134, 190));
        jBuscar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jBuscar.setText("Buscar");
        jBuscar.setBorder(null);
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });
        contenedorVerInmueble.add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 80, 40));

        jValor.setBackground(new java.awt.Color(255, 255, 255));
        jValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 440, 25));
        jValor.getAccessibleContext().setAccessibleDescription("");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Valor de tasacion");
        contenedorVerInmueble.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 155, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cantidad de ambientes");
        contenedorVerInmueble.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 209, -1));

        jAmbientes.setBackground(new java.awt.Color(255, 255, 255));
        jAmbientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jAmbientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 440, 25));
        jAmbientes.getAccessibleContext().setAccessibleDescription("");

        jCubiertos.setBackground(new java.awt.Color(255, 255, 255));
        jCubiertos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jCubiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 440, 25));
        jCubiertos.getAccessibleContext().setAccessibleDescription("");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Metros cuadrados cubiertos");
        contenedorVerInmueble.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 252, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Metros cuadrados totales");
        contenedorVerInmueble.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, -1));

        jTotales.setBackground(new java.awt.Color(255, 255, 255));
        jTotales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 440, 25));
        jTotales.getAccessibleContext().setAccessibleDescription("");

        jIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        jIdentificador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 440, 25));
        jIdentificador.getAccessibleContext().setAccessibleDescription("");

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Antiguedad");
        contenedorVerInmueble.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 110, -1));

        jAntiguedad.setBackground(new java.awt.Color(255, 255, 255));
        jAntiguedad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 440, 25));

        jPiso.setBackground(new java.awt.Color(255, 255, 255));
        jPiso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorVerInmueble.add(jPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 440, 25));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Identificador");
        contenedorVerInmueble.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Piso");
        contenedorVerInmueble.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorVerInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorVerInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverVerInmuebleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverVerInmuebleMouseClicked

    }//GEN-LAST:event_botonVolverVerInmuebleMouseClicked

    private void botonVolverVerInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverVerInmuebleActionPerformed
        this.hide();
        Inmuebles h = new Inmuebles();
        h.setVisible(true);
        botonVolverVerInmueble.setEnabled(false);
    }//GEN-LAST:event_botonVolverVerInmuebleActionPerformed

    private void jDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDniActionPerformed

    private void jDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDireccionActionPerformed

    }//GEN-LAST:event_jDireccionActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
        
        LecturaArchivoInmueble m = new LecturaArchivoInmueble();
        m.cargarCasa();
        m.cargarDepartemento();
        Propiedad p = LecturaArchivoInmueble.accesoADatos().get(jDni.getText());
        if (p != null) {
            if (p instanceof Casa) {
                jDireccion.setText(p.getValorTasacion());
                jValor.setText(p.getDireccion());
                jAmbientes.setText(p.getCantAmbientes());
                jCubiertos.setText(p.getMetrosCuadradosCubiertos());
                jTotales.setText(p.getMetrosCuadradosTotales());
                jAntiguedad.setText(((Casa) p).getAntiguedad());
                jPiso.setText("");
                jPiso.setBackground(Color.GRAY);
                jIdentificador.setText("");
                jIdentificador.setBackground(Color.GRAY);
                jAntiguedad.setBackground(Color.WHITE);
            } else if (p instanceof Departamento) {
                jDireccion.setText(p.getValorTasacion());
                jValor.setText(p.getDireccion());
                jAmbientes.setText(p.getCantAmbientes());
                jCubiertos.setText(p.getMetrosCuadradosCubiertos());
                jTotales.setText(p.getMetrosCuadradosTotales());
                jPiso.setText(((Departamento) p).getPiso());
                jIdentificador.setText(((Departamento) p).getNumero());
                jAntiguedad.setText("");
                jAntiguedad.setBackground(Color.GRAY);
                jPiso.setBackground(Color.WHITE);
                jIdentificador.setBackground(Color.WHITE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe el inmueble de este propietario");
        }

//        LecturaArchivoInmueble m = new LecturaArchivoInmueble();
//        HashMap<String, Propiedad> mapPropiedad = new HashMap<String, Propiedad>();
//        
//        mapPropiedad = m.propiedadCargadaMapa();
//        
//        if(m.controlPropiedad(jDni.getText()) == 1){
//            jDireccion.setText(mapPropiedad.get(jDni.getText()).getValorTasacion());
//            jValor.setText(mapPropiedad.get(jDni.getText()).getDireccion());
//            jAmbientes.setText(mapPropiedad.get(jDni.getText()).getCantAmbientes());
//            jCubiertos.setText(mapPropiedad.get(jDni.getText()).getMetrosCuadradosCubiertos());
//            jTotales.setText(mapPropiedad.get(jDni.getText()).getMetrosCuadradosTotales());
//            jAntiguedad.setText(mapPropiedad.get(jDni.getText().));
//        }
    }//GEN-LAST:event_jBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolverVerInmueble;
    private javax.swing.JPanel contenedorVerInmueble;
    private javax.swing.JTextField jAmbientes;
    private javax.swing.JTextField jAntiguedad;
    private javax.swing.JButton jBuscar;
    private javax.swing.JTextField jCubiertos;
    private javax.swing.JTextField jDireccion;
    private javax.swing.JTextField jDni;
    private javax.swing.JTextField jIdentificador;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPiso;
    private javax.swing.JTextField jTotales;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
